;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"

;= Change directory commands
dev=cd %userprofile%\Dev 
cdc=cd %userprofile%\Dev\5J-Mobile

;= oh-my-zsh git plugins
g=git $*
ga=git add $*
gaa=git add --all
gb=git branch
gbd=git branch -D $*
gc=git commit -v
gcb=git checkout -b $*
gcd=git checkout Development
gcm=git checkout master
gcmsg=git commit -m $*
gco=git checkout $*
gcp=git cherry-pick $*  
gd=git diff
gp=git push $*
ggp=git push origin HEAD
gl=git pull
gm=git merge $*
grhh=git reset HEAD --hard
gst=git status